#!/bin/sh

# lb clean --all
# lb clean noauto --all
# lb config
# lb build

# sudo lb clean --purge
# lb clean noauto --all
sudo lb clean
sudo lb init --distribution jessie
sudo lb config
sudo lb build
