#!/bin/sh

set -e

DISTRIBUTION="ascii"
ARCHITECTURES="amd64"
LINUX_FLAVOURS="amd64"
ARCHIVE_AREAS="main contrib non-free"
SOURCE="false"
# DEVUAN_INSTALLER="live"
DEVUAN_INSTALLER="daily"

SOURCE="false"
_MIRROR_BINARY="http://packages.devuan.org/merged"

# sudo apt-get install apt-cacher-ng
# _MIRROR_BINARY="http://localhost:3142/packages.devuan.org/merged"

# MIRROR_BINARY="http://au.mirror.devuan.org/merged/"
# MIRROR_BINARY="http://packages.devuan.org/devuan/dists/jessie/main/"
# MIRROR_BINARY="http://au.mirror.devuan.org/devuan/dists/jessie/main/"
# MIRROR_BINARY="http://188.165.204.61/repo/dists/jessie/main/"

#	--build-with-chroot false \
#	--debootstrap-options "--variant=minbase"
#	--apt-source-archives true \
#	--initramfs-compression lzma \
#	--apt-options "--force-yes --yes" \
#	--chroot-filesystem squashfs \
# 	--bootappend-install "" \
	#~ --binary-images "iso-hybrid" \	
	#~ --bootloader "syslinux,grub2" \
    #~ --bootloader "grub2" \

# sudo geany /usr/lib/live/build/binary_grub2 /usr/lib/live/build/binary_syslinux /usr/lib/live/build/binary
# sudo geany /usr/lib/live/build/binary_syslinux
# sudo geany /usr/lib/live/build/binary

lb config noauto \
	--mode devuan \
	--chroot-filesystem squashfs \
	--distribution "${_DISTRIBUTION}" \
	--debian-installer-distribution "${_DISTRIBUTION}" \
	--debian-installer "${DEVUAN_INSTALLER}" \
	--architectures "${_ARCHITECTURES}" \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--apt-recommends false \
	--apt-secure true \
	--apt-indices false \
	--apt-source-archives false \
	--archive-areas "${_ARCHIVE_AREAS}" \
	--parent-mirror-bootstrap "${_MIRROR_BINARY}" \
	--parent-mirror-binary "${_MIRROR_BINARY}" \
	--mirror-bootstrap "${_MIRROR_BINARY}" \
	--mirror-binary "${_MIRROR_BINARY}" \
	--iso-application "Star Linux" \
	--iso-publisher "Star" \
	--iso-volume "Star Live" \
	--backports false \
	--security false \
    --updates false \
	--memtest none \
	--win32-loader false \
	--debug \
	--verbose \
	--source "false" \
	--bootappend-live "boot=live config components file=/preseed.cfg quiet splash autologin nouveau.modeset=0 radeon.modeset=0" \
"${@}"
