#!/bin/sh

set -e

_DISTRIBUTION="jessie"
_ARCHITECTURES="amd64"
_LINUX_FLAVOURS="amd64"
_ARCHIVE_AREAS="main contrib non-free"
_SOURCE="false"
_DEVUAN_INSTALLER="live"


# sudo apt-get install apt-cacher-ng
# _MIRROR_BINARY="http://localhost:3142/packages.devuan.org/merged"

_MIRROR_BINARY="http://packages.devuan.org/merged"
# _MIRROR_BINARY="http://pkgmaster.devuan.org/devuan/"
_INSTALLER_MIRROR="http://pkgmaster.devuan.org/devuan/"

# --debootstrap-options "--variant=minbase" \
#	--debian-installer-gui false \
#	--firmware-chroot false \
#	--debian-installer-distribution "${_DISTRIBUTION}" \
#	--debian-installer live \
# 	--initramfs-compression lzma \
    #~ --parent-mirror-chroot "${_INSTALLER_MIRROR}" \
    #~ --mirror-chroot "${_INSTALLER_MIRROR}" \

lb config noauto \
	--mode devuan \
	--clean \
	--chroot-filesystem "squashfs" \
	--initsystem "sysvinit" \
	--bootloaders "syslinux,grub-efi" \
	--distribution "${_DISTRIBUTION}" \
	--debian-installer-distribution "${_DISTRIBUTION}" \
	--debian-installer "${_DEVUAN_INSTALLER}" \
	--architectures "${_ARCHITECTURES}" \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--apt-recommends "false" \
	--apt-secure "true" \
	--apt-indices "false" \
	--apt-source-archives "false" \
	--archive-areas "${_ARCHIVE_AREAS}" \
	--parent-mirror-bootstrap "${_MIRROR_BINARY}" \
	--parent-mirror-binary "${_MIRROR_BINARY}" \
	--mirror-bootstrap "${_MIRROR_BINARY}" \
	--mirror-binary "${_MIRROR_BINARY}" \
    --parent-mirror-debian-installer "${_INSTALLER_MIRROR}" \
    --mirror-debian-installer "${_INSTALLER_MIRROR}" \
    --iso-application "Star Linux" \
	--iso-publisher "Star" \
	--iso-volume "Star Live" \
	--backports "false" \
	--security "false" \
	--updates "false" \
	--memtest "none" \
	--win32-loader "false" \
	--debug \
	--verbose \
	--source "false" \
"${@}"

# lb config --apt-indices false --apt-recommends false --debootstrap-options "--variant=minbase" --firmware-chroot false --memtest none
